---
name: Geo-ICAO
version: 0.36
author:
  - 'Jerome Quelin <jquelin@cpan.org>'
abstract: Airport and ICAO codes lookup
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  perl: 5.008
build_requires:
  Test::More: 0
  perl: 5.008
recommends:
  Test::Kwalitee: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
provides:
  Geo::ICAO:
    file: lib/Geo/ICAO.pm
    version: 0.36
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
